name: inventoryapp
description: "A new Flutter project for inventory management."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  path_provider: ^2.0.8
  provider: ^6.1.2
  path: ^1.8.2
  logging: ^1.1.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  pdf: ^3.6.0 # Check for the latest version
  printing: ^5.7.0 # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
